---
language: bash
services:
  - docker

before_install:
  - chmod +x travis/deploy.sh

# cache:
#   directories:
#     - "$HOME/google-cloud-sdk/"

script:
  - ls -ll
  - travis/deploy.sh


notifications:
  email:
    recipients:
      - yug.soni@searce.com
    on_success: never
    on_failure: always
