arch:
- amd64

language: java

jdk:
- oraclejdk8

os: linux

dist: jammy

sudo: required

services:
- docker

before_install:
  - sudo apt-get update
  - docker build -t test .

script:
- echo "Hello-World"
- mvn test

notifications:
  email:
    - yugjaysoni007@gmail.com