---
language: bash
services:
  - docker
#before_install:
#  - curl https://sdk.cloud.google.com | bash > /dev/null
#  - source "$HOME/google-cloud-sdk/path.bash.inc"
#  - gcloud auth activate-service-account --key-file="${key.json}"
#  - gcloud config set project "thematic-metric-381904"
script:
  - docker build -t springapp-test .
  - docker tag springapp-test:latest
    us-west2-docker.pkg.dev/thematic-metric-381904/travis-test/springapp-test:latest
  - docker push
    us-west2-docker.pkg.dev/thematic-metric-381904/travis-test/springapp-test:latest
notifications:
  email:
    recipients:
      - yug.soni@searce.com
    on_success: never
    on_failure: always