---
language: bash
services:
  - docker

before_install:
#  - curl https://sdk.cloud.google.com | bash > /dev/null
#  - source "$HOME/google-cloud-sdk/path.bash.inc"
#  - gcloud config set project ${PROJECT_ID}
#  - gcloud config set auth/impersonate_service_account ${SA_NAME}
#  - gcloud auth configure-docker \ europe-west2-docker.pkg.dev

# cache:
#   directories:
#     - "$HOME/google-cloud-sdk/"

script:

  # Add gcloud to $PATH
#  - source /home/travis/google-cloud-sdk/path.bash.inc
#  - gcloud version
#  - gcloud config list
#  - gcloud components update
#  - gcloud auth configure-docker europe-west2-docker.pkg.dev -y
  

deploy:
  - provider: script
    script: travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true

notifications:
  email:
    recipients:
      - yug.soni@searce.com
    on_success: never
    on_failure: always
