---
language: bash
services:
  - docker
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=${key.json}
  - gcloud config set project "${PROJECT_ID}"
install:
  - travis_wait 20 mvn install
script:
  - docker build -t springapp-test .
  - docker tag springapp-test:latest
    us-west2-docker.pkg.dev/$PROJECT_ID/travis-test/springapp-test:latest
  - docker push
    us-west2-docker.pkg.dev/$PROJECT_ID/travis-test/springapp-test:latest
notifications:
  email:
    recipients:
      - yug.soni@searce.com
    on_success: never
    on_failure: always
