#### Buiding Docker Image ####
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/$PROJECT_ID/pranav-repo/springapp:v1', '.' ]

#### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/pranav-repo/springapp:v1' ]

#### Deploying Docker Image ####
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['run', 'deploy', 'springservice', '--image', 'asia.gcr.io/$PROJECT_ID/pranav-repo/springapp:v1', '--region', 'asia-south1', '--platform', 'managed', '--allow-unauthenticated']
#images:
#- 'asia.gcr.io/$PROJECT_ID/pranav-repo/springapp:v1'

#### Deploying Docker Image to GKE Cluster ####
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=manifest/
  - --image=asia.gcr.io/searce-playground/pranav-repo/springapp:v1
  - --location=asia-south1-a
  - --cluster=pranav-cicd-test-cluster 
