name: Build and Push images to Artifact Registry
on:
  push:
    branches: [ master ]
jobs:
  build_and_Push:
    runs-on: ubuntu-latest
      #    env:
#      IMAGE_NAME: hello-77
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build and tag Docker image
      run: |
          docker buildx build -t hello-77 .
          docker tag hello-77:latest us-central1-docker.pkg.dev/rare-signer-392411/cicd/hello-77

          # - name: Configure Docker CLI
      # run: |
      #     echo ${{ secrets.SERVICE_ACCOUNT_KEY }} > gcloud-service-key.json
      #     gcloud auth activate-service-account --key-file=gcloud-service-key.json
      #     gcloud config set project ${{ secrets.GOOGLE_PROJECT_ID }}
      #     echo Y | gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Authenticate with GCP
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      

    - name: Push Docker image to Artifact Registry and deploy on Cloud Run
      run: |
         echo Y | gcloud auth configure-docker us-central1-docker.pkg.dev
         docker push us-central1-docker.pkg.dev/rare-signer-392411/cicd/hello-77
         gcloud run deploy cicd-deploy \
         --image=us-central1-docker.pkg.dev/rare-signer-392411/cicd:latest \
         --region=us-central1
         --allow-unauthenticated \
         --service-account=${{ secrets.SERVICE_ACCOUNT_KEY }}
         
